subscribers:
  # Name all the topics to subscribe from in this section. You may also redefine the variable name
  # as long as you can load the yaml variable in your main file
  imu_topic: "/gx5_1/imu/data"
  wheel_encoder_topic: "/joint_states"
  # wheel_radius: 0.1651 # meter
  # wheel_radius: 0.1600 # meter
  wheel_radius: 0.1580 # meter
  # track_width: 0.555 # meter
  track_width: 0.688 # meter

publishers:
  # Define publish rate and topics for publishers
  pose_publish_rate: 1000 # Hz
  pose_publish_topic: "/husky/wheel_odometry/pose"
  pose_frame: "/odom"

  path_publish_rate: 100 # Hz
  path_publish_topic: "/husky/wheel_odometry/path"
