logger:
  # This logger will output a txt file in tum style
  enable_pose_logger: true
  pose_log_file: "/home/neofelis/Code/drift/log/husky.txt"
  pose_log_rate: 10 # Hz

state:
  rotation_std_value: 0.1
  velocity_std_value: 0.1
  position_std_value: 0.001