logger:
  # This logger will output a txt file in tum style
  enable_pose_logger: true
  pose_log_file: "/media/justin/DATA/result/DRIFT_TRO/neya/test.txt"
  vel_log_file: "/media/justin/DATA/result/DRIFT_TRO/neya/test_velocity.txt"
  pose_log_rate: 100 # Hz
state:
  rotation_std_value: 0.1
  velocity_std_value: 0.1
  position_std_value: 0.1
